### ISSUE TITLE
Dashboard screen at the start

### ISSUE THREAD

**Issue by frommberger** [waidyanatha/mobileSAMBRO#1]
The first screen should be a "dashboard screen", showing
- A headline
- the login name
- a big button "Issue new Alert"
- a preview list of the latest alert (maybe the most recent 3, as space permits)

There should be an option to go to the full alert list. Everything besided the preview list should show immediately after logging, and download of alerts must be in the background.

**Comment by anggabayu21** [comment]
can we just put the username inside menu side bar?
i saw the other app like hangout, WA and similar like that they put username inside menu side bar

**Comment by frommberger** [comment]
As we can change users easily and users have different authorities, it is essential to know who you are right from the start. It should be on the main screen.
