### ISSUE TITLE
Build specific files in gitignore

### ISSUE THREAD

**Issue by frommberger** [waidyanatha/mobileSAMBRO#14]
Put all the files that appear in the build process in gitignore, including the APK.

If you want to commit APKs also, use a specific location that is not overwritten by build (I think you already do).

**Comment by anggabayu21** [comment]
yes this kind of things already done

**Comment by frommberger** [comment]
Still, whenever I do a build (cordova build android), I end up with a bunch of local changes under platform/android that prevent me from running clean updates. Isn't it safe to add platforms/ to gitignore?

**Comment by anggabayu21** [comment]
okey, i'll try to test it with different path from my existing path file then i can see the problem.

**Comment by frommberger** [comment]
Works for me.
