### ISSUE TITLE
Offline alert list does not stop loading

### ISSUE THREAD

**Issue by frommberger** [waidyanatha/mobileSAMBRO#21]
The progress bar for the offline alert list shows an endless loading animation.

Situation: First login after installation, no offline alerts in queue. Also happens after logout/re-login.

**Comment by anggabayu21** [comment]
Are you already uninstall the app first?
there some changes in SAMBRO server, so the cached data stored in app is the old data

**Comment by frommberger** [comment]
No I did not. Solved the issue. However, as this might happen in future updates also, there must be a way to update with erasing such data, when server changes are happening.
