### ISSUE TITLE
Automatically trigger alarm via GCM message

### ISSUE THREAD

**Issue by frommberger** [waidyanatha/mobileSAMBRO#25]
In the alert case, the GCM message must be triggered automatically by the SAMBRO server.

**Comment by frommberger** [comment]
pull code from Biplov's repository and create another demo instance /web2py/applications/tempdemo and do not corrupt the /web2py/applications/sambro

**Comment by anggabayu21** [comment]
By now i made small application to do push GCM notification.
Notification will be send to mobile app after the alert approved

**Comment by frommberger** [comment]
Can you give some details about this "app"? Where is it running? How? Is it triggered automatically? What does it do?

**Comment by anggabayu21** [comment]
This app is java background application, it is running in AIT local server. 
This app will get the latest alert approved data and token id client from SAMBRO API every 30 seconds, and stored the value in local small database and further action to send notification to the GCM server.

**Comment by anggabayu21** [comment]
Get latest alert approved data and token_id client from SAMBRO API

**Comment by waidyanatha** [comment]
I created a heavy rain alert on the web and then approved it but did not
hear a siren alarm on my phone. Used the latest app you sent, reinstalled.

Noticed, when you create an alert on the web and save it, before approving
it shows as an alert on the mobile app. Until the alert is approved it is
not published. Only published (i.e.) approved alerts should show on the
mobile alert list.

Might have to come up with a different strategy for saving and displaying
offline or unapproved messages that were edited using the mobile app.

**Comment by anggabayu21** [comment]
You didn't receive an alert notification? my phone was ringing.
What username are you using? 
is this your username "nuwan@sahanafoundation.org"?
i checked in the web sambro you don't have token_id yet, it should be saved automatically by mobile phone app to your SAMBRO web contact person with the contact method is other and desccription is token_id and value should be your token_id value.
are you reinstalled with the uninstalled the application first?
@waidyanatha

**Comment by frommberger** [comment]
I received an altert, 12 minutes after Nuwan complained about not getting one. Does that help? (If not, delete this comment)

**Comment by frommberger** [comment]
@waidyanatha I don't get your comment above - do you talk about alerts created on the app or on the web that show up in the alert list?

**Comment by waidyanatha** [comment]
I created alert using server web app not mobile app. Does that clarify?
