### ISSUE TITLE
Bigger input fields for headline and description

### ISSUE THREAD

**Issue by frommberger** [waidyanatha/mobileSAMBRO#26]
Provide larger input fields for headline/description. In particular, they should be at least as big as the predefined input from the templates.

Actually, only the first line is shown of predefined input.

**Comment by waidyanatha** [comment]
Headline - Although it is not specified in the CAP specification; in general the CAP community restricts the Headline to 140 chars. Therefore, this can be a single line text bow.

Description - is unrestricted and can hold a large story. Typically, the template provides 95% of the description with option to change some event specific values. These values are maintained as placeholders (.e.g A sever category NUMBER tropical cyclone is in effect for AREA... the word NUMBER will be replaced with the actual value to read as ... A category IV Tropical Cyclone is in effect for southern Myanmar)

**Comment by frommberger** [comment]
Some templates provide headlines > 140 chars. Plus, 140 chars do not fit into one line either. We need a larger box.

**Comment by waidyanatha** [comment]
Exactly, it is not a CAP specification to hold the headline to 140 so you could go larger if you want. But that is a norm. OK we make the box bigger!
