### ISSUE TITLE
Change Unique ID

### ISSUE THREAD

**Issue by frommberger** [waidyanatha/mobileSAMBRO#27]
Actually, the unique ID of the app is "com.gic.cap", should be changed to the Sahana name space. 

I would suggest "io.sahana.mobilesambro" or "io.sahana.sambro.mobilesambro".

Ok with this, @waidyanatha?

**Comment by waidyanatha** [comment]
since sahana.io is the website and the if we consider that the space then
sahana.io.sambro.mobile would suffice?

**Comment by frommberger** [comment]
io.sahana.sambro.mobile (in that order), that is also fine with me. Important is that we can uniquely identify the app, as we cannot change it later after it is first published in play store.

**Comment by frommberger** [comment]
Just realized that we need this urgently now, as it's critical for preparing the playstore upload. Can you still realize this, @anggabayu21?

**Comment by anggabayu21** [comment]
Okey... wait

**Comment by anggabayu21** [comment]
DONE .. changed to io.sahana.sambro.mobile
