### ISSUE TITLE
Shorten event type list

### ISSUE THREAD

**Issue by frommberger** [waidyanatha/mobileSAMBRO#3]
Restrict the event type list to pre-defined cases - @waidyanatha should be able to give a list.

Sort list alphabetically.

**Comment by waidyanatha** [comment]
You can JOIN the cap_info table with event_type table on the event_type attribute; that will give you the list of event_types that are associated with a message template.

**Comment by frommberger** [comment]
I think this is to shrink down the template list, that is already done. But we still have ~40 event types, I thought we would want to restrict the cases there as well?

**Comment by waidyanatha** [comment]
​In an actual implementation there are fewer event types. The list on the
demo server is a extended list. For example Maldives has only 4 event types
at the moment.

I don't think @bayu is joining the tables to list the event types. If he
did then the list would be small. It is a 2 step process

1) JOIN the templates and event types to retrieve the event types that have
a template to display the list​ of event types

2) When event type is selected, then display templates that are associated
with the event type

**Comment by frommberger** [comment]
Got it now. Agreed on.
