### ISSUE TITLE
Add server address to settings

### ISSUE THREAD

**Issue by frommberger** [waidyanatha/mobileSAMBRO#31]
User must be able to change the server address in settings.

After changing servers, make sure local data is reset if needed, and newly synced.

**Comment by frommberger** [comment]
Changes:
- show the current URL in the input field (also to give an example of the syntax)

**Comment by anggabayu21** [comment]
it's there .. you should uninstall the app then install again.
or you meant the default value?
i think in the login page we should provide also these feature?
they can change the url before entering the system

**Comment by frommberger** [comment]
I agree, it is good (and important) to add the change server option _before_ login.

Uninstalling the app is not an option, as we are distributing the app through play store. All updates _must_ work with full functionality without an uninstall. What is the reason that the app should be uninstalled first?

**Comment by anggabayu21** [comment]
because the table design changed.
if i drop the table then existing data it will destroy.
or i should create immigration data in the app if there some changed with the database, little bit tricky

**Comment by frommberger** [comment]
Maybe tricky, but essential. At least in Android it's not a big deal, you would call the database migration via "onUpgrade()" - this is only executed if the database version changes.

It is important to keep track of database changes and also change the database version number, plus providing the code to be executed on update.
