### ISSUE TITLE
Map Focus

### ISSUE THREAD

**Issue by waidyanatha** [waidyanatha/mobileSAMBRO#34]
Currently the user has to zoom in (repeatedly) to find the location. In general the app users would be issuing alerts in their local areas and not at a National Level. Therefore they should be able to define the map focus in the "Settings".

There might be a button in the map to click to focus to "My Location" but that may take time load? Is there someway we can allow the user to define their preferred map focus?

Assigned to @frommberger so you can review/revise the issue and then assign to @anggabayu21

**Comment by frommberger** [comment]
I can't really see the issue. Map focus is the current location, and the zoom level was rather too detailed than too course. Worked always fine for me.

However, the "My Location" button is still missing, correct.

**Comment by anggabayu21** [comment]
from where you accessed the app, inside building? you got internet access with wifi or use packet data.
depend on the device itself, if the area is open space you can get your current location faster than inside the building

**Comment by frommberger** [comment]
If we don't have a location, there is not much we can do about it.

Workaround, as suggested by @anggabayu21: fall back to last location we found, if there is none, use the server's location. For now, server location must be hardcoded, but would be a nice feature to have in the SAMBRO server API. 

"Center to current location" button is already there and will get a clearer icon (circle with cross).
