### ISSUE TITLE
Layout incompatible with Android <5

### ISSUE THREAD

**Issue by anggabayu21** [waidyanatha/mobileSAMBRO#37]
webview problem in android version 4.X makes angularjs and material design not work properly

**Comment by anggabayu21** [comment]
@frommberger, i think it will be good if we install the cordova-plugin-crosswalk-webview only for the android < 5 version?
so we will have 2 apk version, i don't know yet it will be easy to maintain or not.

**Comment by frommberger** [comment]
That will most probably be a nightmare to maintain. What does it change to also have it for the 5.x versions?

**Comment by waidyanatha** [comment]
If this is a constraint it needs to be mentioned in the User Guidelines and
in the Blueprint.

**Comment by frommberger** [comment]
Please try to switch to crosswalk. This should have very high priority. Keep us updated about the progress.

**Comment by frommberger** [comment]
1. create a branch for the crosswalk version and push
2. keep master and crosswalk branch in sync
3. I will put a crosswalk and crosswalk release branch to jenkins 
4. crosswalk app will be available as beta version in play store

**Comment by anggabayu21** [comment]
i tried with the android version 4.4.2 the app works well...
without crosswalk

ASUS Tab

**Comment by waidyanatha** [comment]
Can send instructions to Tun to try it in Myanmar

**Comment by frommberger** [comment]
Did you change anything to make it work with 4.4.2?

**Comment by anggabayu21** [comment]
I also tried with the Samsung Galaxy S 3..
Android version 4.4.2 it worked well

both of the devices have a chrome installed.

**Comment by frommberger** [comment]
That is good to hear. But did you change anything to make it work?

Android 4.4 already had a (different) version of webview, so we still need to consider version <4.4

**Comment by anggabayu21** [comment]
I didn't change anything.
I also tried with the Android Version 4.1.2
the function worked well and the design little bit different with the 4.4.2 version and higher.

**Comment by frommberger** [comment]
So what was the issue Tun war reporting then? As I understand, chrome is required to be installed for Android 4.x devices to make the app work?

**Comment by anggabayu21** [comment]
Tun cannot saw the login form at all.
Its too difficult for me to do debug just by screenshoot.

**Comment by frommberger** [comment]
Obviously seems to work. Nobody complained.
