### ISSUE TITLE
Area choice workflow

### ISSUE THREAD

**Issue by frommberger** [waidyanatha/mobileSAMBRO#4]
I propose the following workflow for are choice:
## Initial Screen
- Show a preview map of the current location and chosen areas - is that easily possible? Should take not more than 30-40% of the screen.
- Two buttons: 
  - "Add predefined area"
  - "Draw area on map"
- List of already chosen areas
## Predefined Area Screen
- multiple choice, as done currently
## Draw Area Screen
- directly go to the map to draw area
- enter name _after_ area is submitted, with option to cancel
- (map draw interface will get its own issue, as it is tricky...)

**Comment by frommberger** [comment]
When asking for the area name, also show the drawn polygon on the map.

**Comment by frommberger** [comment]
Another minor thing: when coming to the map, make the "draw polygon" functionality preselected, such that you can start drawing immediately.

**Comment by frommberger** [comment]
The two last points are still unresolved: area name input hides the drawn area, and draw polygon is not preselected.

**Comment by waidyanatha** [comment]
After drawing a polygon half way and deciding to delete the points to start fresh is not possible. One has to start the entire alert from step 1.

**Comment by anggabayu21** [comment]
this is the new bug, after i added preselect draw polygon.

**Comment by anggabayu21** [comment]
i zoom out the polygon when the user click submit button.
