### ISSUE TITLE
Urgency, Severity and Certainty

### ISSUE THREAD

**Issue by biplovbhandari** [waidyanatha/mobileSAMBRO#45]
Presently the urgency, severity and certainty are set only when there is a warning priority. When there is no warning priority, these three elements are set to Null. Ideally the user should be given the options to set or to change those options. Refer to CAP specification V 1.2

**Comment by frommberger** [comment]
I think we agreed on setting urgency, severity and certainty always to the same value, or a corresponding value. I am not sure if this also holds for priority. In any case, the values should be set. @waidyanatha
