### ISSUE TITLE
Settings section

### ISSUE THREAD

**Issue by frommberger** [waidyanatha/mobileSAMBRO#9]
A settings section should be provided that can be easily accessed from the menu.

**Comment by waidyanatha** [comment]
Settings does not provide the option to set the server I want to connect my mobile app to. People in Myanmar should be able to set the app to their SAMBRO and I should be able to set to demo@GIC

**Comment by frommberger** [comment]
We have this already open here:
https://github.com/waidyanatha/mobileSAMBRO/issues/31

Added a milestone, as it's important to have next week.

**Comment by waidyanatha** [comment]
sorry didn't realize. Please delete the one you don't want then
